# Bazel links against newer versions of glibcxx
dist: trusty

os:
  - linux
  - osx

language: c++

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      BAZEL_OS=darwin
    else
      BAZEL_OS=linux
    fi
    BAZEL_URL="https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-installer-$BAZEL_OS-x86_64.sh"
    wget -O install.sh "$BAZEL_URL"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
 - ./presubmit.sh

notifications:
  email: false
